export const Icons = {
  sort: require('../../../assets/sort.png'),
  filter: require('../../../assets/filter.png'),
  select: require('../../../assets/select.png'),
  cancel: require('../../../assets/cancel.png'),
  search: require('../../../assets/search.png'),
  add: require('../../../assets/add.png'),
  grid: require('../../../assets/grid.png'),
  lineGrid: require('../../../assets/grid_2.png'),
  like: require('../../../assets/like.png'),
  menu: require('../../../assets/menu.png'),
  active: require('../../../assets/active.png'),
  carbs: require('../../../assets/carbs.png'),
  proteins: require('../../../assets/proteins.png'),
  fats: require('../../../assets/fats.png'),
  kcal: require('../../../assets/kcal.png'),
  rating: require('../../../assets/rating.png'),
  dot: require('../../../assets/dot.png'),
};
